Repository Snap-Spot/SnapSpot-Frontend, pull requests merged in 2023-09, with the labels that each got.

#18 # 20230830 jiwoorld (곽지우) 페이지네이션 스타일링 통일, 필터링 박스 스타일 수정
  src/components/search/CustomCalender.js
  src/components/search/FilteringBox.js
  src/pages/serach/Pagination.css
  src/pages/serach/Photographerlist.js
Labels: 💄 publishing

#20 # 20230904 wowalswjd (김민정) 메인 페이지 퍼블리싱 및 카카오 로그인 redirect 페이지 ui 수정
  package-lock.json
  package.json
  src/App.js
  src/assets/main/banner1.png
  src/assets/main/banner2.png
  src/assets/main/main_arrow_left.png
  src/assets/main/main_arrow_right.png
  src/assets/main/main_logo.png
  src/components/Main/MainSlider.js
  src/components/Main/RecommendSection.js
  src/pages/LoginPage/KakaoLoginPage.js
  src/pages/MainPage/MainPage.js
Labels: 📝 documentation, 💄 publishing

#24 # 20230907 songing01 (송지민) 작가 검색 자동완성 리스트 퍼블리싱
  src/assets/mypage/modals/search.png
  src/components/Mypage-User/Modals/AddSnapModal.js
  src/components/Mypage-User/Modals/ModalTemplate.js
  src/components/Mypage-User/Modals/SearchList.js
  src/components/Mypage-User/Pick/PhotoBox.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/ReservationItem.js
  src/components/Mypage-User/Reservation/ReservationList.js
  src/components/Photographer/MyPage/MenuList.js
  src/components/Photographer/MyPage/ProfileBox.js
  src/components/Photographer/Reservation/Calendar.js
  src/components/Photographer/Reservation/ScheduleBox.js
  src/components/Photographer/Reservation/UpcomingSchedule.js
  src/components/Photographer/Review/Paging/Paging.css
  src/components/Photographer/Review/Paging/Paging.js
  src/components/Photographer/Setting/Modal.js
  src/components/photographer/Custom/Dropdown.js
  src/components/photographer/Review/ReviewBox.js
  src/pages/MyPage/BestSnapPage.js
  src/pages/MyPage/MyHeartsPage.js
  src/pages/MyPage/SettingsPage.js
  src/pages/MyPage/UserMypage.js
Labels: 💄 publishing

#22 # 20230907 jiwoorld (곽지우) 헤더 및 캐러셀 스타일링 수정
  src/components/common/Header.js
  src/components/common/HomeMenu.js
  src/components/search/EamptySearch.js
  src/components/search/RecommendBox.js
  src/pages/serach/SearchPage.js
Labels: 💄 publishing

#25 # 20230907 songing01 (송지민) 풀 오류 삭제 파일 복구
  src/components/Photographer/MyPage/MenuList.js
  src/components/Photographer/MyPage/ProfileBox.js
  src/components/Photographer/Reservation/Calendar.js
  src/components/Photographer/Reservation/ScheduleBox.js
  src/components/Photographer/Reservation/UpcomingSchedule.js
  src/components/Photographer/Review/Paging/Paging.css
  src/components/Photographer/Review/Paging/Paging.js
  src/components/Photographer/Setting/Modal.js
Labels: 🐛 bugfix, 📝 documentation

#27 # 20230912 songing01 (송지민) api 요청 템플릿 생성
  src/api/client.js
  src/api/photographer.js
Labels: ✨ feature

#28 # 20230912 doozuu (이주희) 작가 관련 페이지 코드 리팩토링 & 반응형 보완
  src/components/Photographers/Custom/BasicInput.js
  src/components/Photographers/Custom/Calendar.js
  src/components/Photographers/Custom/Data/IconList.js
  src/components/Photographers/Custom/FeaturedImgInput.js
  src/components/Photographers/Custom/IntroductionInput.js
  src/components/Photographers/Custom/LocationInput.js
  src/components/Photographers/Custom/NameInput.js
  src/components/Photographers/Custom/OtherInputs.js
  src/components/Photographers/Custom/PriceListInput.js
  src/components/Photographers/Custom/Profile.js
  src/components/Photographers/Custom/SNSInput.js
  src/components/Photographers/Custom/SpecialtyDropdown.js
  src/components/Photographers/Custom/TagInput.js
  src/components/Photographers/Introduction/MockData/CarousalData.js
  src/components/Photographers/Introduction/Profile.js
  src/components/Photographers/Introduction/Review.js
  src/components/Photographers/Introduction/ReviewPhoto.js
  src/components/Photographers/Reservation/Calendar.js
  src/components/Photographers/Reservation/MockData/requestData.js
  src/components/Photographers/Reservation/MockData/reservationData.js
  src/components/Photographers/Reservation/RequestContainer.js
  src/components/Photographers/Reservation/ReservationContainer.js
  src/components/Photographers/Reservation/UpcomingContainer.js
  src/components/Photographers/Reservation/UpcomingSchedule.js
  src/components/Photographers/ReservationDetail/ChatBox.js
  src/components/Photographers/ReservationDetail/ScheduleDetail.js
  src/components/Photographers/Review/MockData/ReviewData.js
  src/components/Photographers/Review/ReviewBox.js
  src/components/common/LayOut.js
  src/pages/Photographer/Custom.js
  src/pages/Photographer/Introduction.js
  src/pages/Photographer/MyPage.js
  src/pages/Photographer/RequestList.js
  src/pages/Photographer/Reservation.js
  src/pages/Photographer/ReservationDetail.js
  src/pages/Photographer/ReservationList.js
  src/pages/Photographer/Review.js
  src/pages/Photographer/Setting.js
Labels: 👀 enhancement, 💄 publishing

#29 # 20230915 jiwoorld (곽지우) 검색, 사진 작가 페이지 퍼블리싱 및 반응형 수정
  src/App.js
  src/api/search.js
  src/components/common/Header.js
  src/components/common/HomeMenu.js
  src/components/search/EamptySearch.js
  src/components/search/FilteringBox.js
  src/components/search/RecommendBox.js
  src/components/search/SearchBox.js
  src/components/search/data/PhotographerListData.js
  src/components/search/data/SearchData.js
  src/pages/serach/Photographerlist.js
  src/pages/serach/SearchPage.js
Labels: 📝 documentation, ✨ feature, 👀 enhancement

#30 # 20230918 jiwoorld (곽지우) 검색 페이지, 사진작가 리스트 페이지 API 연결
  src/api/client.js
  src/api/search.js
  src/components/common/HomeMenu.js
  src/components/common/category.js
  src/components/search/CustomCalendar.js
  src/components/search/FilteringBox.js
  src/components/search/FilteringList.js
  src/components/search/SearchBox.js
  src/components/search/data/PhotographerListData.js
  src/components/search/data/SearchData.js
  src/pages/serach/Photographerlist.js
  src/pages/serach/SearchPage.js
Labels: ✨ feature, 💄 publishing

#31 20230918 songing01 (송지민) 예약내역 리스트 페이지, 예약내역상세 페이지, 마이페이지 API 연결
  package-lock.json
  src/api/member.js
  src/api/photographer.js
  src/api/plan.js
  src/components/Mypage-User/Modals/SearchList.js
  src/components/Mypage-User/Mypage/ProfileContainer.js
  src/components/Mypage-User/Pick/MySnapBox.js
  src/components/Mypage-User/Pick/MySnaps.js
  src/components/Mypage-User/Reservation/DetailMenus.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/ReservationItem.js
  src/components/Mypage-User/Reservation/ReservationList.js
  src/components/common/TranslateCategory.js
  src/components/common/TranslateStatus.js
  src/pages/MyPage/UserMypage.js
  src/pages/SpotListPage/SpotListPage.js
Labels: ✨ feature

#32 20230919 wowalswjd (김민정) 일반 로그인/회원가입 api 연결
  src/api/auth.js
  src/components/Login/LoginForm.js
  src/components/SignUp/SignUpForm.js
  src/components/common/SignUpLoginBtn.style.js
Labels: ✨ feature, 💄 publishing

#33 20230919 songing01 (송지민) 이미지 S3 업로드, 좋아요 모아보기 get api연결
  src/api/heart.js
  src/api/member.js
  src/api/s3upload.js
  src/assets/mypage/modals/add.png
  src/components/Mypage-User/Modals/AddSnapModal.js
  src/components/Mypage-User/Modals/ReceiptModal.js
  src/components/Mypage-User/Mypage/SettingsForm.js
  src/components/Mypage-User/Reservation/DetailMenus.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/ReservationItem.js
  src/pages/MyPage/MyHeartsPage.js
Labels: ✨ feature

#36 20230924 wowalswjd (김민정) 회원가입/로그인 페이지에 로고만 있는 헤더 추가
  src/api/member.js
  src/api/url.js
  src/components/common/Header.js
  src/pages/LoginPage/LoginPage.js
  src/pages/SignUpPage/SignUpInfoPage.js
  src/pages/SignUpPage/SignUpMemberPage.js
Labels: ✨ feature, 💄 publishing

#37 # 20230926 jiwoorld (곽지우) 필터링박스 sort 추가, 불필요한 코드/파일 삭제
  src/api/search.js
  src/components/common/category.js
  src/components/search/FilteringBox.js
  src/components/search/FilteringList.js
  src/components/search/RecommendBox.js
  src/pages/serach/Photographerlist.js
  src/pages/serach/SearchPage.js
Labels: 📝 documentation, ✨ feature

#39 20230926 songing01 (송지민) 베스트 스냅 모아보기, 등록하기, 예약취소, 피드 api 연결
  src/api/area.js
  src/api/best-snap.js
  src/api/plan.js
  src/components/Mypage-User/Modals/AddSnapModal.js
  src/components/Mypage-User/Modals/CancelModal.js
  src/components/Mypage-User/Modals/Dropdown.js
  src/components/Mypage-User/Modals/ReceiptModal.js
  src/components/Mypage-User/Modals/SearchList.js
  src/components/Mypage-User/Pick/MySnapBox.js
  src/components/Mypage-User/Pick/MySnaps.js
  src/components/Mypage-User/Reservation/DetailMenus.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/ReservationItem.js
  src/components/SpotList/SpotBox.js
  src/components/SpotList/SpotList.js
Labels: ✨ feature
