Repository Snap-Spot/SnapSpot-Frontend, pull requests merged in 2023-08, with the labels that each got.

#1 # 20230812 doozuu (이주희) title 변경
  public/index.html
Labels: 📝 documentation

#2 # 20230812 jiwoorld (곽지우) Header 퍼블리싱
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/logo.png
  src/assets/menu.png
  src/assets/profile.png
  src/assets/search.png
  src/components/common/Header.js
  src/components/common/HomeMenu.js
  src/index.css
  src/index.js
  src/styles/Font.css
  src/styles/global.css
Labels: 📝 documentation, 💄 publishing

#3 # 20230816 doozuu (이주희) Header 수정 및 작가예약내역 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.js
  src/assets/logo.png
  src/assets/photograph/Footer.png
  src/assets/photograph/arrow.png
  src/assets/photograph/calendar.png
  src/assets/photograph/line.png
  src/assets/photograph/profile.png
  src/assets/search.png
  src/components/Photograph/ScheduleBox.js
  src/components/Photograph/UpcomingSchedule.js
  src/components/common/Header.js
  src/index.js
  src/pages/photographer/Reservation.js
  src/pages/photographer/ReservationDetail.js
Labels: 📝 documentation, 💄 publishing

#4 20230817 jiwoorld (곽지우) Header 수정
  src/assets/header/logo.png
  src/assets/header/menu.png
  src/assets/header/mobilelogo.png
  src/assets/header/profile.png
  src/assets/header/search.png
  src/components/common/Header.js
  src/components/common/HomeMenu.js
Labels: 📝 documentation, 💄 publishing

#5 # 20230819 wowalswjd (김민정) global.css 적용 및 회원가입 페이지 퍼블리싱
  src/App.js
  src/assets/signup/customer.png
  src/assets/signup/customer_mobile.png
  src/assets/signup/kakao.png
  src/assets/signup/photographer.png
  src/assets/signup/photographer_mobile.png
  src/components/SignUp/SignUpForm.js
  src/index.js
  src/pages/SignUpInfoPage.js
  src/pages/SignUpMemberPage.js
  src/styles/Font.css
Labels: 📝 documentation, 💄 publishing

#6 20230819 songing01 (송지민) 예약 내역 페이지, 예약 내역 상세페이지, 공용 푸터 컴포넌트 퍼블리싱, 글로벌 스타일 설정
  src/App.js
  src/assets/common/footerLogo.png
  src/assets/common/inquiry.png
  src/assets/mypage/reservation/arrow.png
  src/components/Reservation/DetailMenus.js
  src/components/Reservation/DetailedItem.js
  src/components/Reservation/Dropdown.js
  src/components/Reservation/ReservationItem.js
  src/components/Reservation/ReservationList.js
  src/components/common/Footer.js
  src/index.js
  src/pages/MyPage/DetailReservePage.js
  src/pages/MyPage/MyReservePage.js
  src/styles/global.css
Labels: 📝 documentation, 💄 publishing

#7 20230819 jiwoorld (곽지우) 검색 후 페이지 퍼블리싱
  src/App.js
  src/assets/header/profile.png
  src/assets/search/calendar.png
  src/assets/search/glass.png
  src/assets/search/more.png
  src/assets/search/photo.jpeg
  src/assets/search/reviewIcon.png
  src/assets/search/starIcon.png
  src/components/common/Header.js
  src/components/search/EamptySearch.js
  src/components/search/FilteringBox.js
  src/components/search/RecommendBox.js
  src/components/search/SearchBox.js
  src/pages/serach/Photographerlist.js
  src/pages/serach/SearchPage.js
  src/styles/Font.css
Labels: 💄 publishing

#10 20230823 jiwoorld (곽지우) 작가리스트 페이지, 필터링 컴포넌트, 커스텀 캘린더 퍼블리싱
  package-lock.json
  package.json
  src/assets/search/nextarrow.png
  src/assets/search/previousarrow.png
  src/components/common/Header.js
  src/components/search/CustomCalender.js
  src/components/search/EamptySearch.js
  src/components/search/FilteringBox.js
  src/components/search/FilteringList.js
  src/components/search/RecommendBox.js
  src/pages/serach/Photographerlist.js
  src/pages/serach/SearchPage.js
  src/styles/Font.css
Labels: 📝 documentation, 💄 publishing

#11 # 20230825 doozuu (이주희) 작가 관련 페이지 5개 퍼블리싱
  package-lock.json
  package.json
  src/App.js
  src/assets/photograph/deleteIcon.png
  src/assets/photograph/dropdown.png
  src/assets/photograph/ex_profile.png
  src/assets/photograph/icon1.png
  src/assets/photograph/icon2.png
  src/assets/photograph/icon3.png
  src/assets/photograph/imgPlus.png
  src/assets/photograph/next_btn.png
  src/assets/photograph/plus.png
  src/assets/photograph/prev_btn.png
  src/assets/photograph/setting.png
  src/assets/photograph/star.png
  src/assets/photograph/warn.png
  src/components/Photographer/MyPage/Dropdown.js
  src/components/Photographer/MyPage/Modal.js
  src/components/Photographer/MyPage/Paging/Paging.css
  src/components/Photographer/MyPage/Paging/Paging.js
  src/components/Photographer/MyPage/ReviewBox.js
  src/components/Photographer/Reservation/Calendar.js
  src/components/Photographer/Reservation/ScheduleBox.js
  src/components/Photographer/Reservation/ScheduleDetail.js
  src/components/Photographer/Reservation/UpcomingSchedule.js
  src/pages/photographer/Custom.js
  src/pages/photographer/MyPage.js
  src/pages/photographer/Reservation.js
  src/pages/photographer/ReservationDetail.js
  src/pages/photographer/Review.js
  src/pages/photographer/Setting.js
Labels: 💄 publishing

#12 # 20230827 wowalswjd (김민정) 카카오 로그인 토큰 발급 기능 추가 및 로그인/회원가입 ui 리팩토링
  package-lock.json
  package.json
  src/App.js
  src/assets/signup/loading.png
  src/components/Login/KakaoLoginBtn.js
  src/components/Login/LoginForm.js
  src/components/SignUp/SignUpForm.js
  src/components/common/SignUpLoginBtn.style.js
  src/pages/LoginPage/KakaoLoginPage.js
Labels: 📝 documentation, ✨ feature, 💄 publishing

#13 # 20230828 jiwoorld (곽지우) 작가리스트 페이지네이션 및 추천 작가 리스트 캐러셀 구현
  package-lock.json
  package.json
  src/assets/search/ic_left.png
  src/assets/search/ic_right.png
  src/components/common/Header.js
  src/components/search/EamptySearch.js
  src/components/search/FilteringBox.js
  src/pages/serach/Pagination.css
  src/pages/serach/Photographerlist.js
Labels: 💄 publishing

#14 # 20230828 doozuu (이주희) 코드 리팩토링
  package-lock.json
  src/App.js
  src/components/Photographer/Custom/Dropdown.js
  src/components/Photographer/MyPage/MenuList.js
  src/components/Photographer/MyPage/ProfileBox.js
  src/components/Photographer/Reservation/Calendar.js
  src/components/Photographer/Reservation/ScheduleBox.js
  src/components/Photographer/Reservation/ScheduleDetail.js
  src/components/Photographer/Reservation/UpcomingSchedule.js
  src/components/Photographer/Review/Paging/Paging.css
  src/components/Photographer/Review/Paging/Paging.js
  src/components/Photographer/Review/ReviewBox.js
  src/components/Photographer/Setting/Modal.js
  src/pages/photographer/Custom.js
  src/pages/photographer/MyPage.js
  src/pages/photographer/Reservation.js
  src/pages/photographer/ReservationDetail.js
  src/pages/photographer/Review.js
  src/pages/photographer/Setting.js
Labels: 👀 enhancement

#15 # 20230829 doozuu (이주희) 폴더명 대소문자 오류 해결
  src/pages/Photographer/Custom.js
  src/pages/Photographer/MyPage.js
  src/pages/Photographer/Reservation.js
  src/pages/Photographer/ReservationDetail.js
  src/pages/Photographer/Review.js
  src/pages/Photographer/Setting.js
Labels: 🐛 bugfix
