Repository Snap-Spot/SnapSpot-Frontend, pull requests merged in 2023-10, with the labels that each got.

#40 # 20230928 jiwoorld (곽지우) 사진 작가 필터링 페이지 url 접근 추가, Footer 디자인 변경, 파비콘 추가, 좋아요 API 연결
  public/favicon.ico
  src/api/heart.js
  src/api/search.js
  src/assets/common/git.png
  src/assets/common/instagram.png
  src/assets/photograph/clickedheart.png
  src/components/Photographers/Introduction/Profile.js
  src/components/common/Footer.js
  src/components/search/FilteringBox.js
  src/components/search/SearchBox.js
  src/pages/Photographer/Introduction.js
  src/pages/serach/Photographerlist.js
Labels: ✨ feature

#42 # 20231003 jiwoorld (곽지우) Header 기능 수정
  package-lock.json
  src/App.js
  src/components/common/Header.js
  src/components/common/Loading.js
  src/components/common/LoadingContext.js
  src/components/common/SearchBox.js
  src/pages/serach/Photographerlist.js
  src/pages/serach/SearchPage.js
Labels: ✨ feature

#44 #20231007 songing01 (송지민) 리뷰 등록,작가에게 문의하기,메세지조회,예약변경 api 연결, 카카오지도 필드값추가
  src/api/member.js
  src/api/message.js
  src/api/plan.js
  src/api/review.js
  src/components/Mypage-User/Modals/ChangeModal.js
  src/components/Mypage-User/Modals/MiniCalendar.js
  src/components/Mypage-User/Modals/ModalTemplate.js
  src/components/Mypage-User/Modals/QuestionModal.js
  src/components/Mypage-User/Modals/ReviewModal.js
  src/components/Mypage-User/Mypage/SettingsForm.js
  src/components/Mypage-User/Pick/PhotoBox.js
  src/components/Mypage-User/Reservation/ChatsContainer.js
  src/components/Mypage-User/Reservation/DetailMenus.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/KakaoMap.js
  src/components/Mypage-User/Reservation/MyChat.js
  src/components/Mypage-User/Reservation/YourChat.js
  src/pages/MyPage/MyHeartsPage.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing

#45 #20231007 jiwoorld (곽지우) 사진작가 상세 페이지 뒤로가기 클릭시 페이지 넘버 유지
  src/components/common/Header.js
  src/components/search/FilteringBox.js
  src/pages/serach/Photographerlist.js
Labels: 🐛 bugfix

#46 #20231008 doozuu (이주희) 파일 전달, 리뷰 조회 api 연결
  src/api/photographer.js
  src/api/plan.js
  src/components/Photographers/Custom/BasicInput.js
  src/components/Photographers/Custom/Calendar.js
  src/components/Photographers/Custom/FeaturedImgInput.js
  src/components/Photographers/Custom/OtherInputs.js
  src/components/Photographers/Custom/PriceListInput.js
  src/components/Photographers/Custom/Profile.js
  src/components/Photographers/Introduction/Filtering.js
  src/components/Photographers/Introduction/PriceModal.js
  src/components/Photographers/Introduction/Profile.js
  src/components/Photographers/Introduction/ReservationModal.js
  src/components/Photographers/Introduction/Review.js
  src/components/Photographers/Introduction/ReviewPhoto.js
  src/components/Photographers/Introduction/ex.js
  src/components/Photographers/Reservation/Calendar.js
  src/components/Photographers/Reservation/MockData/status.js
  src/components/Photographers/Reservation/ReservationContainer.js
  src/components/Photographers/Reservation/ScheduleBox.js
  src/components/Photographers/Reservation/UpcomingSchedule.js
  src/components/Photographers/ReservationDetail/ChatBox.js
  src/components/Photographers/ReservationDetail/FileInputModal.js
  src/components/Photographers/ReservationDetail/PhotoChatBox.js
  src/components/Photographers/ReservationDetail/ScheduleDetail.js
  src/components/Photographers/Review/Paging/Paging.css
  src/components/Photographers/Review/Paging/Paging.js
  src/components/Photographers/Review/ReviewBox.js
  src/components/common/category.js
  src/pages/Photographer/Custom.js
  src/pages/Photographer/Introduction.js
  src/pages/Photographer/Reservation.js
  src/pages/Photographer/ReservationDetail.js
  src/pages/Photographer/Review.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing

#48 #20231008 songing01 (송지민) 최대 예약인원 설정, 오류 수정, 로딩중 ui 추가
  src/api/best-snap.js
  src/api/heart.js
  src/api/member.js
  src/api/plan.js
  src/components/Mypage-User/Modals/AddSnapModal.js
  src/components/Mypage-User/Modals/Dropdown.js
  src/components/Mypage-User/Modals/MiniCalendar.js
  src/components/Mypage-User/Mypage/MyMenu.js
  src/components/Mypage-User/Mypage/SettingsForm.js
  src/components/Mypage-User/Pick/MySnaps.js
  src/components/Mypage-User/Reservation/DetailMenus.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/DropdownFilter.js
  src/components/Mypage-User/Reservation/KakaoMap.js
  src/components/Mypage-User/Reservation/MyChat.js
  src/components/Mypage-User/Reservation/ReservationItem.js
  src/components/Mypage-User/Reservation/ReservationList.js
  src/components/SpotList/SpotList.js
  src/pages/MyPage/MyHeartsPage.js
  src/pages/MyPage/SettingsPage.js
  src/pages/MyPage/UserMypage.js
Labels: 🐛 bugfix, ✨ feature

#49 20231008 wowalswjd (김민정) 메인 페이지 api 연결 및 마이페이지 접근 제한 기능 구현
  src/App.js
  src/api/auth.js
  src/assets/main/couple.png
  src/assets/main/family.png
  src/assets/main/family2.png
  src/assets/main/friendship.png
  src/assets/main/graduation.png
  src/assets/main/wedding.png
  src/assets/main/wedding2.png
  src/components/Login/LoginForm.js
  src/components/Main/RecommendSection.js
  src/components/Main/RecommendSnapBox.js
  src/components/Route/PrivateRoute.js
  src/components/common/category.js
  src/pages/MainPage/MainPage.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing

#51 20231010 songing01 (송지민) 로딩중ui 추가, 사이즈 통일
  src/components/Main/RecommendSection.js
  src/components/Mypage-User/Pick/MySnaps.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/ReservationList.js
  src/components/SpotList/SpotList.js
  src/components/common/Loading.js
  src/components/search/FilteringBox.js
  src/components/search/FilteringList.js
  src/pages/LoginPage/KakaoLoginPage.js
  src/pages/MyPage/MyHeartsPage.js
  src/pages/SignUpPage/KakaoSignUpPage.js
  src/pages/serach/SearchPage.js
Labels: ✨ feature, 💄 publishing

#52 # 20231010 jiwoorld (곽지우) 필터링 박스 기능 수정, input 스타일 변경
  src/components/common/SearchBox.js
  src/components/search/CustomCalendar.js
  src/components/search/FilteringBox.js
  src/styles/global.css
Labels: ✨ feature, 💄 publishing

#55 20231010 songing01 (송지민) 카카오 지도 http block 오류 수정, 피드 제목 수정, 프로필 이미지 널일때 예외처리
  public/index.html
  src/components/Mypage-User/Mypage/ProfileContainer.js
  src/components/Mypage-User/Mypage/SettingsForm.js
  src/pages/SpotListPage/SpotListPage.js
Labels: 🐛 bugfix, 💄 publishing

#57 # 20231010 songing01 (송지민) 가격 숫자 포맷, 메인에 올렸던 내용 머지
  public/index.html
  src/components/Main/RecommendSection.js
  src/components/Mypage-User/Modals/CancelModal.js
  src/components/Mypage-User/Modals/ReceiptModal.js
  src/components/Mypage-User/Mypage/ProfileContainer.js
  src/components/Mypage-User/Mypage/SettingsForm.js
  src/components/Mypage-User/Pick/MySnaps.js
  src/components/Mypage-User/Reservation/DetailedItem.js
  src/components/Mypage-User/Reservation/ReservationList.js
  src/components/SpotList/SpotList.js
  src/components/common/Loading.js
  src/pages/LoginPage/KakaoLoginPage.js
  src/pages/MyPage/MyHeartsPage.js
  src/pages/SignUpPage/KakaoSignUpPage.js
  src/pages/SpotListPage/SpotListPage.js
  src/pages/serach/SearchPage.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing

#58 # 20231011 jiwoorld (곽지우) 헤더 기본 프로필 오류 해결, 사진작가 리스트 스타일링 수정
  src/components/Photographers/Introduction/Profile.js
  src/components/Photographers/Reservation/ScheduleBox.js
  src/components/Photographers/Reservation/UpcomingSchedule.js
  src/components/Photographers/ReservationDetail/ChatBox.js
  src/components/Photographers/ReservationDetail/MinInputModal.js
  src/components/Photographers/ReservationDetail/PhotoChatBox.js
  src/components/Photographers/ReservationDetail/ScheduleDetail.js
  src/components/Photographers/Review/ReviewBox.js
  src/components/common/Footer.js
  src/components/common/Header.js
  src/components/common/HomeMenu.js
  src/components/search/EamptySearch.js
  src/components/search/FilteringBox.js
  src/components/search/RecommendBox.js
  src/components/search/SearchBox.js
  src/components/search/data/PhotographerListData.js
  src/components/search/data/SearchData.js
  src/pages/Photographer/Review.js
  src/pages/serach/Photographerlist.js
Labels: 🐛 bugfix, 💄 publishing

#59 # 20231011 doozuu (이주희) 작가 관련 페이지 모바일 뷰 스타일링 보완
  src/assets/photograph/dot.png
  src/components/Photographers/Custom/BasicInput.js
  src/components/Photographers/Custom/Data/IconList.js
  src/components/Photographers/Custom/FeaturedImgInput.js
  src/components/Photographers/Custom/IntroductionInput.js
  src/components/Photographers/Custom/LowestPriceInput.js
  src/components/Photographers/Custom/NameInput.js
  src/components/Photographers/Custom/Profile.js
  src/components/Photographers/Custom/RegionInput.js
  src/components/Photographers/Custom/SNSInput.js
  src/components/Photographers/Custom/SpecialtyDropdown.js
  src/components/Photographers/Introduction/Filtering.js
  src/components/Photographers/Introduction/PriceModal.js
  src/components/Photographers/Introduction/Profile.js
  src/components/Photographers/Introduction/Review.js
  src/components/Photographers/Introduction/ReviewFiltering.js
  src/components/Photographers/Introduction/ReviewPhoto.js
  src/components/Photographers/Introduction/SNS.js
  src/components/Photographers/Introduction/ex.js
  src/components/Photographers/Reservation/Calendar.js
  src/components/Photographers/Reservation/RequestContainer.js
  src/components/Photographers/Reservation/ReservationContainer.js
  src/components/Photographers/Reservation/ScheduleBox.js
  src/components/Photographers/Reservation/ScheduleDetail.js
  src/components/Photographers/Reservation/UpcomingContainer.js
  src/components/Photographers/Reservation/UpcomingSchedule.js
  src/components/Photographers/ReservationDetail/FileInputModal.js
  src/components/Photographers/ReservationDetail/MinInputModal.js
  src/components/Photographers/ReservationDetail/RejectModal.js
  src/components/Photographers/ReservationDetail/ScheduleDetail.js
  src/components/Photographers/Review/ReviewBox.js
  src/pages/Photographer/Custom.js
  src/pages/Photographer/Introduction.js
  src/pages/Photographer/RequestList.js
  src/pages/Photographer/Reservation.js
  src/pages/Photographer/ReservationDetail.js
  src/pages/Photographer/ReservationList.js
  src/pages/Photographer/Review.js
Labels: ✨ feature, 💄 publishing

#61 # 20231012 songing01 (송지민) 모바일에서 브라우저 기본 푸터에 가려 끝까지 스크롤이 안되는 이슈 해결
  src/components/Mypage-User/Modals/ModalTemplate.js
Labels: 💄 publishing

#62 #20231012 doozuu (이주희) 모바일 뷰 스타일링 깨지는 부분 수정
  src/components/Photographers/Custom/Calendar.js
  src/components/Photographers/Introduction/PriceModal.js
  src/components/Photographers/Introduction/Profile.js
  src/components/Photographers/Introduction/ReservationModal.js
  src/components/Photographers/Introduction/Review.js
  src/components/Photographers/Reservation/Calendar.js
  src/components/Photographers/Review/ReviewBox.js
  src/pages/Photographer/Introduction.js
Labels: 💄 publishing

#65 #20231013 jiwoorld (곽지우) 경고 해결, 스타일링 수정
  src/components/common/Header.js
  src/components/common/HomeMenu.js
  src/components/common/SearchBox.js
  src/components/search/FilteringBox.js
  src/components/search/SearchBox.js
  src/pages/serach/SearchPage.js
Labels: 🐛 bugfix, 💄 publishing

#66 #20231014 doozuu (이주희) 작가 관련 페이지 스타일링 수정
  src/components/Photographers/Custom/Calendar.js
  src/components/Photographers/Custom/RegionInput.js
  src/components/Photographers/Custom/TagInput.js
  src/components/Photographers/Introduction/PriceModal.js
  src/components/Photographers/Introduction/Profile.js
  src/components/Photographers/Introduction/ReservationModal.js
  src/components/Photographers/Introduction/Review.js
  src/components/Photographers/Introduction/SNS.js
  src/components/Photographers/Reservation/Calendar.js
  src/components/Photographers/Reservation/ScheduleBox.js
  src/components/Photographers/Reservation/UpcomingSchedule.js
  src/components/Photographers/ReservationDetail/AddressSearch.js
  src/components/Photographers/ReservationDetail/ScheduleDetail.js
  src/components/Photographers/Review/ReviewBox.js
  src/pages/Photographer/Custom.js
Labels: 💄 publishing

#67 20231015 wowalswjd (김민정) 할인 쿠폰 페이지 퍼블리싱 및 Google Analytics 기능 적용
  package-lock.json
  package.json
  src/App.js
  src/assets/event/wedding_coupon.png
  src/components/Event/EventItem.js
  src/components/Main/MainSlider.js
  src/components/Main/RecommendSnapBox.js
  src/components/Route/RouteChangeTracker.js
  src/components/common/category.js
  src/components/search/RecommendBox.js
  src/pages/EventPage/EventPage.js
Labels: ✨ feature, 💄 publishing

#70 #20231017 songing01 (송지민) 우정스냅 영문명 수정
  src/components/common/TranslateCategory.js
Labels: 🐛 bugfix

#72 #20231017 jiwoorld (곽지우) 문의하기, 인스타그램 링크 연결
  src/components/common/Footer.js
  src/components/common/HomeMenu.js
Labels: ✨ feature

#75 #20231017 songing01 (송지민) 작가에게 문의하기-> 작가에게 메세지 보내기로 텍스트 변경
  src/components/Mypage-User/Modals/QuestionModal.js
  src/components/Mypage-User/Reservation/DetailMenus.js
Labels: 💄 publishing

#76 20231018 wowalswjd (김민정) SEO 관련 문서 추가/수정, 메인 페이지 추천 작가 지역 제주로 수정
  public/index.html
  public/robots.txt
  public/snapspot.png
  src/api/client.js
  src/components/Route/RouteChangeTracker.js
  src/pages/MainPage/MainPage.js
Labels: 🐛 bugfix, 📝 documentation, ✨ feature

#78 20231020 wowalswjd (김민정) 토큰 재발급 오류 수정, NotFoundPage 추가, MainPage 새로운 배너 연결
  src/App.js
  src/api/client.js
  src/assets/event/coupon.png
  src/assets/event/wedding_coupon.png
  src/assets/main/banner2.png
  src/assets/main/banner_graduation.png
  src/assets/main/banner_jeju.png
  src/assets/main/banner_new_member.png
  src/assets/main/banner_october.png
  src/assets/main/banner_wedding.png
  src/assets/main/family2.png
  src/assets/main/wedding2.png
  src/assets/signup/arrow_left.png
  src/components/Event/EventItem.js
  src/components/Login/LoginForm.js
  src/components/Main/MainSlider.js
  src/pages/EventPage/EventPage.js
  src/pages/MainPage/MainPage.js
  src/pages/NotFoundPage/NotFoundPage.js
  src/pages/SignUpPage/KakaoSignUpPage.js
  src/pages/SignUpPage/SignUpMemberPage.js
Labels: 🐛 bugfix, ✨ feature, 💄 publishing
